Lesson8
Dmitry-Ischenko/ASP.NET.L1 pull request #10
Opened 2020-12-25 14:55 UTC by Dmitry-Ischenko

в процессе

2020-12-25 14:56 UTC, Dmitry-Ischenko commented
начало

2020-12-26 09:54 UTC, Infarh requested changes
Нужно доделать сервис заказов. Он потребуется далее...

2020-12-26 14:30 UTC, Dmitry-Ischenko commented
> Нужно доделать сервис заказов. Он потребуется далее...

я пока не начинал 8 урок

2020-12-26 14:30 UTC, merged

2020-12-26 14:32 UTC, Dmitry-Ischenko commented
что-то я не понял, закрыл пулрексевт по 7 уроку, а закрылся и 8й